name: build alist with vListUI

on:
  push:
    branches: [ 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.21' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup deno
        run: |
          curl -L https://github.com/denoland/deno/releases/download/v1.45.5/deno-x86_64-unknown-linux-gnu.zip -o deno.zip
          unzip deno.zip
          rm deno.zip
          mv deno ~/deno 
          chmod +x ~/deno

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: ~/deno run -A --unstable ./setup.ts

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: 'latest'
          tag: ${{ github.ref }}
          overwrite: true
          body: "这是已经编译完成的版本"
          file: ~/dist/*
          file_glob: true