name: build alist with vListUI

on:
  push:
    branches: [ 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.21' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup deno
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}


      - name: Build
        run: deno run -A --unstable setup.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alist_${{ env.SHA }}
          path: dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: 'latest'
          tag: ${{ github.ref }}
          overwrite: true
          body: "这是已经编译完成的版本"
          file: /dist/*
          file_glob: true